// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gomart.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBonusAccount = `-- name: CreateBonusAccount :exec
INSERT INTO bonus_accounts (user_id, current_balance, total_bonuses_spent)
VALUES (
    (SELECT id FROM users WHERE username = $1 LIMIT 1),
    $2,
    $3
)
`

type CreateBonusAccountParams struct {
	Username          string
	CurrentBalance    float32
	TotalBonusesSpent float32
}

// Bonus Accounts --
func (q *Queries) CreateBonusAccount(ctx context.Context, arg CreateBonusAccountParams) error {
	_, err := q.db.Exec(ctx, createBonusAccount, arg.Username, arg.CurrentBalance, arg.TotalBonusesSpent)
	return err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (oid, user_id, status, uploaded_at, updated_at)
VALUES (
    $1,
    (SELECT id FROM users WHERE username = $2 LIMIT 1),
    $3,
    $4,
    $5
)
`

type CreateOrderParams struct {
	Oid        int64
	Username   string
	Status     string
	UploadedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.Oid,
		arg.Username,
		arg.Status,
		arg.UploadedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAll = `-- name: GetAll :many
SELECT users.username, orders.oid, orders.status, orders.accrual, orders.uploaded_at
FROM orders
JOIN users ON orders.user_id = users.id
`

type GetAllRow struct {
	Username   string
	Oid        int64
	Status     string
	Accrual    pgtype.Float4
	UploadedAt pgtype.Timestamptz
}

// ORDERS --
func (q *Queries) GetAll(ctx context.Context) ([]GetAllRow, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.Username,
			&i.Oid,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrdersForAccrual = `-- name: GetAllOrdersForAccrual :many

SELECT users.username, orders.oid, orders.status, orders.accrual, orders.uploaded_at
FROM orders
JOIN users ON orders.user_id = users.id
WHERE orders.status NOT IN ('PROCESSED', 'INVALID')
`

type GetAllOrdersForAccrualRow struct {
	Username   string
	Oid        int64
	Status     string
	Accrual    pgtype.Float4
	UploadedAt pgtype.Timestamptz
}

// Accrual --
func (q *Queries) GetAllOrdersForAccrual(ctx context.Context) ([]GetAllOrdersForAccrualRow, error) {
	rows, err := q.db.Query(ctx, getAllOrdersForAccrual)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrdersForAccrualRow
	for rows.Next() {
		var i GetAllOrdersForAccrualRow
		if err := rows.Scan(
			&i.Username,
			&i.Oid,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalanceByOrderID = `-- name: GetBalanceByOrderID :one
SELECT u.username, ba.current_balance, ba.total_bonuses_spent
FROM bonus_accounts ba
JOIN orders o ON o.user_id = ba.user_id
JOIN users u ON o.user_id = u.id
WHERE o.oid = $1
`

type GetBalanceByOrderIDRow struct {
	Username          string
	CurrentBalance    float32
	TotalBonusesSpent float32
}

func (q *Queries) GetBalanceByOrderID(ctx context.Context, oid int64) (GetBalanceByOrderIDRow, error) {
	row := q.db.QueryRow(ctx, getBalanceByOrderID, oid)
	var i GetBalanceByOrderIDRow
	err := row.Scan(&i.Username, &i.CurrentBalance, &i.TotalBonusesSpent)
	return i, err
}

const getBalanceByUserName = `-- name: GetBalanceByUserName :one
SELECT current_balance, total_bonuses_spent
FROM bonus_accounts
JOIN users ON users.id = bonus_accounts.user_id
WHERE users.username = $1
FOR UPDATE
`

type GetBalanceByUserNameRow struct {
	CurrentBalance    float32
	TotalBonusesSpent float32
}

func (q *Queries) GetBalanceByUserName(ctx context.Context, username string) (GetBalanceByUserNameRow, error) {
	row := q.db.QueryRow(ctx, getBalanceByUserName, username)
	var i GetBalanceByUserNameRow
	err := row.Scan(&i.CurrentBalance, &i.TotalBonusesSpent)
	return i, err
}

const getBonusTransactionsByUserName = `-- name: GetBonusTransactionsByUserName :many
SELECT oid, bonuses_withdraw, processed_at
FROM bonus_transactions bt
JOIN bonus_accounts ba ON bt.bonus_id = ba.id
JOIN users u ON ba.user_id = u.id
WHERE u.username = $1
ORDER BY bt.processed_at DESC
`

type GetBonusTransactionsByUserNameRow struct {
	Oid             int64
	BonusesWithdraw float32
	ProcessedAt     pgtype.Timestamptz
}

func (q *Queries) GetBonusTransactionsByUserName(ctx context.Context, username string) ([]GetBonusTransactionsByUserNameRow, error) {
	rows, err := q.db.Query(ctx, getBonusTransactionsByUserName, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBonusTransactionsByUserNameRow
	for rows.Next() {
		var i GetBonusTransactionsByUserNameRow
		if err := rows.Scan(&i.Oid, &i.BonusesWithdraw, &i.ProcessedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByOID = `-- name: GetOrderByOID :one
SELECT users.username, orders.oid, orders.status, orders.accrual, orders.uploaded_at
FROM orders
JOIN users ON orders.user_id = users.id
WHERE orders.oid = $1
LIMIT 1
`

type GetOrderByOIDRow struct {
	Username   string
	Oid        int64
	Status     string
	Accrual    pgtype.Float4
	UploadedAt pgtype.Timestamptz
}

func (q *Queries) GetOrderByOID(ctx context.Context, oid int64) (GetOrderByOIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByOID, oid)
	var i GetOrderByOIDRow
	err := row.Scan(
		&i.Username,
		&i.Oid,
		&i.Status,
		&i.Accrual,
		&i.UploadedAt,
	)
	return i, err
}

const getOrdersByUserName = `-- name: GetOrdersByUserName :many
SELECT OID, status, accrual, uploaded_at
FROM orders
JOIN users ON users.id = orders.user_id
WHERE users.username = $1
`

type GetOrdersByUserNameRow struct {
	Oid        int64
	Status     string
	Accrual    pgtype.Float4
	UploadedAt pgtype.Timestamptz
}

func (q *Queries) GetOrdersByUserName(ctx context.Context, username string) ([]GetOrdersByUserNameRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserName, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserNameRow
	for rows.Next() {
		var i GetOrdersByUserNameRow
		if err := rows.Scan(
			&i.Oid,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByUserName = `-- name: GetRefreshTokenByUserName :one
SELECT user_tokens.token_id, user_tokens.is_valid
FROM user_tokens
JOIN users ON users.id = user_tokens.user_id
WHERE users.username = $1
LIMIT 1
`

type GetRefreshTokenByUserNameRow struct {
	TokenID string
	IsValid bool
}

// TOKEN --
func (q *Queries) GetRefreshTokenByUserName(ctx context.Context, username string) (GetRefreshTokenByUserNameRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByUserName, username)
	var i GetRefreshTokenByUserNameRow
	err := row.Scan(&i.TokenID, &i.IsValid)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

// USERS --
func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT password_hash FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserPassword(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getUserPassword, username)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, password_hash, created_at, updated_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBonusTransaction = `-- name: InsertBonusTransaction :exec
INSERT INTO bonus_transactions (bonus_id, oid, bonuses_withdraw, processed_at)
SELECT ba.id, $2, $3, $4
FROM users u
JOIN bonus_accounts ba ON ba.user_id = u.id
WHERE u.username = $1
LIMIT 1
`

type InsertBonusTransactionParams struct {
	Username        string
	Oid             int64
	BonusesWithdraw float32
	ProcessedAt     pgtype.Timestamptz
}

// Bonus Transactions --
func (q *Queries) InsertBonusTransaction(ctx context.Context, arg InsertBonusTransactionParams) error {
	_, err := q.db.Exec(ctx, insertBonusTransaction,
		arg.Username,
		arg.Oid,
		arg.BonusesWithdraw,
		arg.ProcessedAt,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO user_tokens (user_id, token_id, is_valid)
VALUES (
    (SELECT id FROM users WHERE username = $1 LIMIT 1),
    $2,
    $3
)
`

type InsertRefreshTokenParams struct {
	Username string
	TokenID  string
	IsValid  bool
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.Username, arg.TokenID, arg.IsValid)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (username, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4)
`

type InsertUserParams struct {
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE bonus_accounts SET current_balance = $1, total_bonuses_spent = $2
WHERE user_id = (SELECT id FROM users WHERE username = $3 LIMIT 1)
`

type UpdateBalanceParams struct {
	CurrentBalance    float32
	TotalBonusesSpent float32
	Username          string
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.CurrentBalance, arg.TotalBonusesSpent, arg.Username)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET  status = $1, accrual = $2
WHERE oid = $3
`

type UpdateOrderStatusParams struct {
	Status  string
	Accrual pgtype.Float4
	Oid     int64
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.Accrual, arg.Oid)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE user_tokens
SET token_id = $1, is_valid = $2
WHERE user_id = (SELECT id FROM users WHERE username = $3 LIMIT 1)
`

type UpdateRefreshTokenParams struct {
	TokenID  string
	IsValid  bool
	Username string
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.TokenID, arg.IsValid, arg.Username)
	return err
}

const updateRefreshTokenIsValid = `-- name: UpdateRefreshTokenIsValid :exec
UPDATE user_tokens SET is_valid = $1
WHERE user_id = (SELECT id FROM users WHERE username = $2 LIMIT 1)
`

type UpdateRefreshTokenIsValidParams struct {
	IsValid  bool
	Username string
}

func (q *Queries) UpdateRefreshTokenIsValid(ctx context.Context, arg UpdateRefreshTokenIsValidParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenIsValid, arg.IsValid, arg.Username)
	return err
}
