// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BonusAccount struct {
	ID                int32
	UserID            int32
	CurrentBalance    int32
	TotalBonusesSpent int32
}

type BonusTransaction struct {
	ID              int32
	BonusID         int32
	OrderID         int32
	BonusesWithdraw int32
	ProcessedAt     pgtype.Timestamptz
}

type Order struct {
	ID         int32
	UserID     int32
	Oid        int64
	Status     string
	Accrual    pgtype.Int4
	UploadedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserToken struct {
	ID      int32
	UserID  int32
	TokenID string
	IsValid bool
}
