// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AA122AA/gomart.git/internal/db/query"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceRepo creates a new instance of MockBalanceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepo {
	mock := &MockBalanceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceRepo is an autogenerated mock type for the BalanceRepo type
type MockBalanceRepo struct {
	mock.Mock
}

type MockBalanceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepo) EXPECT() *MockBalanceRepo_Expecter {
	return &MockBalanceRepo_Expecter{mock: &_m.Mock}
}

// GetBonusTransactions provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) GetBonusTransactions(ctx context.Context, username string) ([]query.GetBonusTransactionsByUserNameRow, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetBonusTransactions")
	}

	var r0 []query.GetBonusTransactionsByUserNameRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]query.GetBonusTransactionsByUserNameRow, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []query.GetBonusTransactionsByUserNameRow); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]query.GetBonusTransactionsByUserNameRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepo_GetBonusTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBonusTransactions'
type MockBalanceRepo_GetBonusTransactions_Call struct {
	*mock.Call
}

// GetBonusTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockBalanceRepo_Expecter) GetBonusTransactions(ctx interface{}, username interface{}) *MockBalanceRepo_GetBonusTransactions_Call {
	return &MockBalanceRepo_GetBonusTransactions_Call{Call: _e.mock.On("GetBonusTransactions", ctx, username)}
}

func (_c *MockBalanceRepo_GetBonusTransactions_Call) Run(run func(ctx context.Context, username string)) *MockBalanceRepo_GetBonusTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_GetBonusTransactions_Call) Return(getBonusTransactionsByUserNameRows []query.GetBonusTransactionsByUserNameRow, err error) *MockBalanceRepo_GetBonusTransactions_Call {
	_c.Call.Return(getBonusTransactionsByUserNameRows, err)
	return _c
}

func (_c *MockBalanceRepo_GetBonusTransactions_Call) RunAndReturn(run func(ctx context.Context, username string) ([]query.GetBonusTransactionsByUserNameRow, error)) *MockBalanceRepo_GetBonusTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) GetByUser(ctx context.Context, username string) (query.GetBalanceByUserNameRow, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 query.GetBalanceByUserNameRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (query.GetBalanceByUserNameRow, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) query.GetBalanceByUserNameRow); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(query.GetBalanceByUserNameRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepo_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockBalanceRepo_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockBalanceRepo_Expecter) GetByUser(ctx interface{}, username interface{}) *MockBalanceRepo_GetByUser_Call {
	return &MockBalanceRepo_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, username)}
}

func (_c *MockBalanceRepo_GetByUser_Call) Run(run func(ctx context.Context, username string)) *MockBalanceRepo_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_GetByUser_Call) Return(getBalanceByUserNameRow query.GetBalanceByUserNameRow, err error) *MockBalanceRepo_GetByUser_Call {
	_c.Call.Return(getBalanceByUserNameRow, err)
	return _c
}

func (_c *MockBalanceRepo_GetByUser_Call) RunAndReturn(run func(ctx context.Context, username string) (query.GetBalanceByUserNameRow, error)) *MockBalanceRepo_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawTransaction provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) WithdrawTransaction(ctx context.Context, username string, oid int, amount float32) error {
	ret := _mock.Called(ctx, username, oid, amount)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, float32) error); ok {
		r0 = returnFunc(ctx, username, oid, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceRepo_WithdrawTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawTransaction'
type MockBalanceRepo_WithdrawTransaction_Call struct {
	*mock.Call
}

// WithdrawTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - oid int
//   - amount float32
func (_e *MockBalanceRepo_Expecter) WithdrawTransaction(ctx interface{}, username interface{}, oid interface{}, amount interface{}) *MockBalanceRepo_WithdrawTransaction_Call {
	return &MockBalanceRepo_WithdrawTransaction_Call{Call: _e.mock.On("WithdrawTransaction", ctx, username, oid, amount)}
}

func (_c *MockBalanceRepo_WithdrawTransaction_Call) Run(run func(ctx context.Context, username string, oid int, amount float32)) *MockBalanceRepo_WithdrawTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 float32
		if args[3] != nil {
			arg3 = args[3].(float32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_WithdrawTransaction_Call) Return(err error) *MockBalanceRepo_WithdrawTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceRepo_WithdrawTransaction_Call) RunAndReturn(run func(ctx context.Context, username string, oid int, amount float32) error) *MockBalanceRepo_WithdrawTransaction_Call {
	_c.Call.Return(run)
	return _c
}
