// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AA122AA/gomart.git/internal/db/query"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

type MockOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepo) EXPECT() *MockOrderRepo_Expecter {
	return &MockOrderRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) Create(ctx context.Context, OID int, username string, status string) error {
	ret := _mock.Called(ctx, OID, username, status)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, OID, username, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - OID int
//   - username string
//   - status string
func (_e *MockOrderRepo_Expecter) Create(ctx interface{}, OID interface{}, username interface{}, status interface{}) *MockOrderRepo_Create_Call {
	return &MockOrderRepo_Create_Call{Call: _e.mock.On("Create", ctx, OID, username, status)}
}

func (_c *MockOrderRepo_Create_Call) Run(run func(ctx context.Context, OID int, username string, status string)) *MockOrderRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepo_Create_Call) Return(err error) *MockOrderRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepo_Create_Call) RunAndReturn(run func(ctx context.Context, OID int, username string, status string) error) *MockOrderRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) Get(ctx context.Context, ouid int) (query.GetOrderByOIDRow, error) {
	ret := _mock.Called(ctx, ouid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 query.GetOrderByOIDRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (query.GetOrderByOIDRow, error)); ok {
		return returnFunc(ctx, ouid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) query.GetOrderByOIDRow); ok {
		r0 = returnFunc(ctx, ouid)
	} else {
		r0 = ret.Get(0).(query.GetOrderByOIDRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, ouid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ouid int
func (_e *MockOrderRepo_Expecter) Get(ctx interface{}, ouid interface{}) *MockOrderRepo_Get_Call {
	return &MockOrderRepo_Get_Call{Call: _e.mock.On("Get", ctx, ouid)}
}

func (_c *MockOrderRepo_Get_Call) Run(run func(ctx context.Context, ouid int)) *MockOrderRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_Get_Call) Return(getOrderByOIDRow query.GetOrderByOIDRow, err error) *MockOrderRepo_Get_Call {
	_c.Call.Return(getOrderByOIDRow, err)
	return _c
}

func (_c *MockOrderRepo_Get_Call) RunAndReturn(run func(ctx context.Context, ouid int) (query.GetOrderByOIDRow, error)) *MockOrderRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) GetAll(ctx context.Context) ([]query.GetAllRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []query.GetAllRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]query.GetAllRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []query.GetAllRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]query.GetAllRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockOrderRepo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderRepo_Expecter) GetAll(ctx interface{}) *MockOrderRepo_GetAll_Call {
	return &MockOrderRepo_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockOrderRepo_GetAll_Call) Run(run func(ctx context.Context)) *MockOrderRepo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderRepo_GetAll_Call) Return(getAllRows []query.GetAllRow, err error) *MockOrderRepo_GetAll_Call {
	_c.Call.Return(getAllRows, err)
	return _c
}

func (_c *MockOrderRepo_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]query.GetAllRow, error)) *MockOrderRepo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) GetByUser(ctx context.Context, username string) ([]query.GetOrdersByUserNameRow, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []query.GetOrdersByUserNameRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]query.GetOrdersByUserNameRow, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []query.GetOrdersByUserNameRow); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]query.GetOrdersByUserNameRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockOrderRepo_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockOrderRepo_Expecter) GetByUser(ctx interface{}, username interface{}) *MockOrderRepo_GetByUser_Call {
	return &MockOrderRepo_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, username)}
}

func (_c *MockOrderRepo_GetByUser_Call) Run(run func(ctx context.Context, username string)) *MockOrderRepo_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_GetByUser_Call) Return(getOrdersByUserNameRows []query.GetOrdersByUserNameRow, err error) *MockOrderRepo_GetByUser_Call {
	_c.Call.Return(getOrdersByUserNameRows, err)
	return _c
}

func (_c *MockOrderRepo_GetByUser_Call) RunAndReturn(run func(ctx context.Context, username string) ([]query.GetOrdersByUserNameRow, error)) *MockOrderRepo_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}
