// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AA122AA/gomart.git/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateRefreshToken(ctx context.Context, tokenID string, username string, isvalid bool) error {
	ret := _mock.Called(ctx, tokenID, username, isvalid)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, tokenID, username, isvalid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockUserRepo_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - username string
//   - isvalid bool
func (_e *MockUserRepo_Expecter) CreateRefreshToken(ctx interface{}, tokenID interface{}, username interface{}, isvalid interface{}) *MockUserRepo_CreateRefreshToken_Call {
	return &MockUserRepo_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, tokenID, username, isvalid)}
}

func (_c *MockUserRepo_CreateRefreshToken_Call) Run(run func(ctx context.Context, tokenID string, username string, isvalid bool)) *MockUserRepo_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateRefreshToken_Call) Return(err error) *MockUserRepo_CreateRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string, username string, isvalid bool) error) *MockUserRepo_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserAndBonusAcc provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateUserAndBonusAcc(ctx context.Context, username string, passwordHash string, balance float32, spent float32) error {
	ret := _mock.Called(ctx, username, passwordHash, balance, spent)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserAndBonusAcc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float32, float32) error); ok {
		r0 = returnFunc(ctx, username, passwordHash, balance, spent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_CreateUserAndBonusAcc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserAndBonusAcc'
type MockUserRepo_CreateUserAndBonusAcc_Call struct {
	*mock.Call
}

// CreateUserAndBonusAcc is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - passwordHash string
//   - balance float32
//   - spent float32
func (_e *MockUserRepo_Expecter) CreateUserAndBonusAcc(ctx interface{}, username interface{}, passwordHash interface{}, balance interface{}, spent interface{}) *MockUserRepo_CreateUserAndBonusAcc_Call {
	return &MockUserRepo_CreateUserAndBonusAcc_Call{Call: _e.mock.On("CreateUserAndBonusAcc", ctx, username, passwordHash, balance, spent)}
}

func (_c *MockUserRepo_CreateUserAndBonusAcc_Call) Run(run func(ctx context.Context, username string, passwordHash string, balance float32, spent float32)) *MockUserRepo_CreateUserAndBonusAcc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float32
		if args[3] != nil {
			arg3 = args[3].(float32)
		}
		var arg4 float32
		if args[4] != nil {
			arg4 = args[4].(float32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateUserAndBonusAcc_Call) Return(err error) *MockUserRepo_CreateUserAndBonusAcc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_CreateUserAndBonusAcc_Call) RunAndReturn(run func(ctx context.Context, username string, passwordHash string, balance float32, spent float32) error) *MockUserRepo_CreateUserAndBonusAcc_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasswordHash provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetPasswordHash(ctx context.Context, username string) (string, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetPasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordHash'
type MockUserRepo_GetPasswordHash_Call struct {
	*mock.Call
}

// GetPasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepo_Expecter) GetPasswordHash(ctx interface{}, username interface{}) *MockUserRepo_GetPasswordHash_Call {
	return &MockUserRepo_GetPasswordHash_Call{Call: _e.mock.On("GetPasswordHash", ctx, username)}
}

func (_c *MockUserRepo_GetPasswordHash_Call) Run(run func(ctx context.Context, username string)) *MockUserRepo_GetPasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetPasswordHash_Call) Return(s string, err error) *MockUserRepo_GetPasswordHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserRepo_GetPasswordHash_Call) RunAndReturn(run func(ctx context.Context, username string) (string, error)) *MockUserRepo_GetPasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByUserName provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetRefreshTokenByUserName(ctx context.Context, username string) (*domain.GetRefreshTokenID, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByUserName")
	}

	var r0 *domain.GetRefreshTokenID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.GetRefreshTokenID, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.GetRefreshTokenID); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetRefreshTokenID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetRefreshTokenByUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByUserName'
type MockUserRepo_GetRefreshTokenByUserName_Call struct {
	*mock.Call
}

// GetRefreshTokenByUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepo_Expecter) GetRefreshTokenByUserName(ctx interface{}, username interface{}) *MockUserRepo_GetRefreshTokenByUserName_Call {
	return &MockUserRepo_GetRefreshTokenByUserName_Call{Call: _e.mock.On("GetRefreshTokenByUserName", ctx, username)}
}

func (_c *MockUserRepo_GetRefreshTokenByUserName_Call) Run(run func(ctx context.Context, username string)) *MockUserRepo_GetRefreshTokenByUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetRefreshTokenByUserName_Call) Return(getRefreshTokenID *domain.GetRefreshTokenID, err error) *MockUserRepo_GetRefreshTokenByUserName_Call {
	_c.Call.Return(getRefreshTokenID, err)
	return _c
}

func (_c *MockUserRepo_GetRefreshTokenByUserName_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.GetRefreshTokenID, error)) *MockUserRepo_GetRefreshTokenByUserName_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateRefreshToken provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) InvalidateRefreshToken(ctx context.Context, username string) error {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_InvalidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateRefreshToken'
type MockUserRepo_InvalidateRefreshToken_Call struct {
	*mock.Call
}

// InvalidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepo_Expecter) InvalidateRefreshToken(ctx interface{}, username interface{}) *MockUserRepo_InvalidateRefreshToken_Call {
	return &MockUserRepo_InvalidateRefreshToken_Call{Call: _e.mock.On("InvalidateRefreshToken", ctx, username)}
}

func (_c *MockUserRepo_InvalidateRefreshToken_Call) Run(run func(ctx context.Context, username string)) *MockUserRepo_InvalidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_InvalidateRefreshToken_Call) Return(err error) *MockUserRepo_InvalidateRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_InvalidateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, username string) error) *MockUserRepo_InvalidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRefreshToken provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateRefreshToken(ctx context.Context, tokenID string, username string, isvalid bool) error {
	ret := _mock.Called(ctx, tokenID, username, isvalid)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, tokenID, username, isvalid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRefreshToken'
type MockUserRepo_UpdateRefreshToken_Call struct {
	*mock.Call
}

// UpdateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - username string
//   - isvalid bool
func (_e *MockUserRepo_Expecter) UpdateRefreshToken(ctx interface{}, tokenID interface{}, username interface{}, isvalid interface{}) *MockUserRepo_UpdateRefreshToken_Call {
	return &MockUserRepo_UpdateRefreshToken_Call{Call: _e.mock.On("UpdateRefreshToken", ctx, tokenID, username, isvalid)}
}

func (_c *MockUserRepo_UpdateRefreshToken_Call) Run(run func(ctx context.Context, tokenID string, username string, isvalid bool)) *MockUserRepo_UpdateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateRefreshToken_Call) Return(err error) *MockUserRepo_UpdateRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string, username string, isvalid bool) error) *MockUserRepo_UpdateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
