-- +goose Up
-- +goose StatementBegin
--
CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"username" TEXT NOT NULL UNIQUE,
	"password_hash" TEXT NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL,
	"updated_at" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "orders" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"oid" INTEGER NOT NULL,
	"status" TEXT NOT NULL,
	"accrual" INTEGER,
	"uploaded_at" TIMESTAMPTZ NOT NULL,
	"updated_at" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "bonus_accounts" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"current_balance" INTEGER NOT NULL,
	"total_bonuses_spent" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "bonus_transactions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"bonus_id" INTEGER NOT NULL,
	"order_id" INTEGER NOT NULL,
	"bonuses_withdraw" INTEGER NOT NULL,
	"processed_at" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "user_tokens" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL UNIQUE,
	"token_id" TEXT NOT NULL,
	"is_valid" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);

ALTER TABLE "orders"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bonus_accounts"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bonus_transactions"
ADD FOREIGN KEY("bonus_id") REFERENCES "bonus_accounts"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_tokens"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE users;
DROP TABLE orders;
DROP TABLE bonus_accounts;
DROP TABLE bonus_transactions;
DROP TABLE user_tokens;
-- +goose StatementEnd
